type                = "directrequest"
schemaVersion       = 1
name                = "Get FlightStatuses"
contractAddress     = "0xd006d393b49f89677722Ed04A26Ab83C74B1aC0e"
observationSource   = """
"""
